### ISSUE TITLE
error al instalar

### ISSUE THREAD

**Issue by rockdrigo** [conekta/conekta-magento#13]
sale este error al instalar

Checking dependencies of packages

CONNECT ERROR: Package 'Conekta_Payment_Extension' is invalid
'./app/design\frontend\base\default\template\checkout\success.phtml' already exists

**Comment by MauricioMurga** [comment]
Hola @rockdrigo, este bug ya no debe existir en este https://github.com/conekta/conekta-magento/commit/4ac7ac193b7eacbce73c9ed17364dfb47adba26b.
