### ISSUE TITLE
traduccion

### ISSUE THREAD

**Issue by rockdrigo** [conekta/conekta-magento#14]
Mauricio,

para la próxima actualización del plugin de magento podrías agregar

"This is a required field.","Este es un Campo necesario."

o alguna traduccion similar 
al archivo de traducción ;)

saludos

**Comment by MauricioMurga** [comment]
Gracias!, agregaré pronto el cambio!

**Comment by MauricioMurga** [comment]
Listo! 973008f3b27432dbb1efd43d2d54e5bf745c3b80
