### ISSUE TITLE
Fix 

### ISSUE THREAD

**Issue by Janee** [conekta/conekta-magento#15]
1. En el archivo -> "
   ​_app\code\community\Conekta\Webhook\Block\Adminhtml\Sales\Order\View\Tab\Info.php_​
   "
2. Agregar después del "​_if_​" un "​_else_​" y poner esta línea de
   código "return
   parent::getPaymentHtml();"

Eso es todo. Con eso ya no se omitirá la información de otros métodos de
pago en las ordenes del administrador.

**Comment by cyberChakal** [comment]
Ok, gracias por el dato

**Comment by MauricioMurga** [comment]
https://github.com/conekta/conekta-magento/commit/2a43c372b7f818d7df71a4f3b149ecabba718e45
