### ISSUE TITLE
401 response in conekta admin

### ISSUE THREAD

**Issue by babyasishhira** [conekta/conekta-magento#53]
Hi,
I am getting 401 response in conekta admin, As a result payment status not is being updated.

For more details please check below screenshot 

- http://prntscr.com/i805f0

- http://prntscr.com/i805kl

My php version is 5.6.33. Using live mode

Please let me know for anything else if you want to know about this issue.

**Comment by mauroarcet** [comment]
Hi @babyasishhira the error is in the wrong configuration of the webhook. 

If you want to add an extra webhook (which we don't support) your server must return an HTTP 200 code.

**Comment by babyasishhira** [comment]
Thank you
