### ISSUE TITLE
Instalación Manual

### ISSUE THREAD

**Issue by t1gr3ju4n** [conekta/conekta-magento#54]
Hola, tengo Magento 2.1.9, cuando voy al Component Manager, aparece Conekta pero manda errores de instalación, tuvo el mismo problema con otra extensión pero pude habilitarla de forma manual, hay algún método para instalar Conekta de esta forma?

**Comment by lu1s** [comment]
Hola @t1gr3ju4n . Qué vresión del plugin estás intentando instalar? Qué versión de php y extensiones tienes? Y podrías compartir los logs para más detalles? Saludos.

**Comment by t1gr3ju4n** [comment]
Hola Luis, tengo Magento 2.1.9, la versión de PHP es 5.6 con los plugins de la imagen.

![captura de pantalla 2018-02-06 a la s 18 24 36](https://user-images.githubusercontent.com/20493847/35891665-1b8c415c-0b6b-11e8-8c9c-29aca7aebc07.png)

**Comment by lu1s** [comment]
Y cuales son los errores de instalación?

**Comment by t1gr3ju4n** [comment]
![captura de pantalla 2018-02-06 a la s 18 29 50](https://user-images.githubusercontent.com/20493847/35891818-c1c329d2-0b6b-11e8-8bee-a1b9710c1f43.png)

**Comment by lu1s** [comment]
Creo que son problemas de permisos o de dependencias en tu ambiente. @eduardoconekta Sabes qué puede ser?

**Comment by t1gr3ju4n** [comment]
Intenté la instalación desde shell que viene en el zip, pero me pide credenciales, ya utilicé las de Market de Magento, las del Admin de mi tienda y las de github y con ninguna me deja.

![captura de pantalla 2018-02-06 a la s 18 34 29](https://user-images.githubusercontent.com/20493847/35892009-e73b5382-0b6c-11e8-88c2-39bba28678d2.png)

![captura de pantalla 2018-02-06 a la s 18 40 28](https://user-images.githubusercontent.com/20493847/35892078-3c3da574-0b6d-11e8-8c60-1d92598ae8bd.png)

**Comment by lu1s** [comment]
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html

**Comment by t1gr3ju4n** [comment]
Gracias Luis, es normal este mensaje?

![captura de pantalla 2018-02-06 a la s 18 56 22](https://user-images.githubusercontent.com/20493847/35892570-8bf57626-0b6f-11e8-9da6-7d3885c59569.png)

**Comment by lu1s** [comment]
Me imagino que sí. @eduardoconekta sabe más de los plugins y librerías

**Comment by t1gr3ju4n** [comment]
Pues se lo pasó por el arco del triunfo XD

![captura de pantalla 2018-02-06 a la s 19 03 10](https://user-images.githubusercontent.com/20493847/35892749-6dd137a6-0b70-11e8-8a50-8113aed880a0.png)

**Comment by lu1s** [comment]
Según yo es este repo: https://github.com/conekta/conekta-magento2 y este thread está en https://github.com/conekta/conekta-magento.

Para instalar indica estas instrucciones:

Installation
-----------

1. First add this repository in your composer config

    ```bash
    composer config repositories.conekta git https://github.com/conekta/conekta-magento2.git
    ```
2. Add the dependency

    ```bash
    composer require conekta/conekta_payments dev-master
    ```
3. Update your Magento

    ```bash
    php bin/magento setup:upgrade
    ```
4. Compile your XML files

    ```bash
    php bin/magento setup:di:compile
    ```
    
Updates
-----------

For update this plugin execute the next command

```bash
php bin/magento setup:upgrade # version bump
php bin/magento setup:di:compile # version bump
composer update conekta/magento2-module
```

**Comment by eduardoconekta** [comment]
tus api keys son las mismas que te proporciona la tienda al momento de comprar el producto me parece @t1gr3ju4n podrías intentarlo de esa forma ?

**Comment by QuiqueM** [comment]
funciona en magento 2.3.5p1?

**Comment by laloas2004** [comment]
A mi me funciono asi,  en la carpeta app/code creas una carpetas llamadas Conekta/Payments y ahi descomprimes el modulo que bajas de magento marketplace, luego ejecutas el comando **php bin/magento setup:upgrade** y luego el comando **php -d memory_limit=-1 bin/magento setup:di:compile**
