### ISSUE TITLE
No se muestra codigo de barras

### ISSUE THREAD

**Issue by AdanRuiz** [conekta/conekta-magento#55]
bar code is not shown after place an order.
Magento versión 1.9.3.2
![badorderoxxo](https://user-images.githubusercontent.com/606012/37002861-b33e0686-2090-11e8-9a4f-7cd37cd31749.png)

**Comment by mauroarcet** [comment]
Hola @AdanRuiz con OXXO Pay no necesitas un código de barras, es por eso que no se está mostrando. 
Tu cliente solo tiene que dictar el número de referencia al cajero en OXXO,

¡Saludos!
