### ISSUE TITLE
Error en el Manejo de Impuestos

### ISSUE THREAD

**Issue by MrDavidChz** [conekta/conekta-magento#61]
Toda mi tienda no maneja ningún tipo de impuesto, porque ya lo tiene incluido en su precio publicado .
pero en algunos productos me marca el siguiente error.
![image](https://user-images.githubusercontent.com/34451939/40379818-d38cbee6-5dbc-11e8-8f55-848a04af83df.png)

Revisando el log en Conekta el error me parece que esta en el resultado del  monto.
![image](https://user-images.githubusercontent.com/34451939/40379905-22010352-5dbd-11e8-9822-6ba293d8271d.png)

Alguna solución ?

**Comment by edenriquez** [comment]
Hola @MrDavidChz el problema esta en los centavos que estan en el Tax del producto al aplicar la siguiente regla
```
(intval($item->getTaxAmount() * 10000 )/ 100);
```
(en nuestro plugin) haremos unas pruebas y sacaremos el fix en caso de que aplique, lo que te puedo comentar es que como menciono el item tiene un amount en su propiedad tax por que en caso de que no tuviera no estaria entrando en el proceso que recaba los taxes, podrías imprimir el tax del producto para poder debuggearlo ? es decir imprimir en algún lugar 
```
$item->getTaxAmount() 
```
para confirmar que si esta trayendo un tax o que no en caso de que sea realmente un bug de nuestro lado procederia a abrir un caso para atender esto.

**Comment by MrDavidChz** [comment]
Mira al parecer el taxAmount esta en 0 , es curioso solo pasa en algunos productos.

![image](https://user-images.githubusercontent.com/34451939/40383825-73983910-5dc7-11e8-96fa-9fc076b32c50.png)

![image](https://user-images.githubusercontent.com/34451939/40383846-8319d1f0-5dc7-11e8-86a2-cdf6fe6d9fc3.png)

**Comment by edenriquez** [comment]
@MrDavidChz  ok podrías imprimir `floatval($item->getTaxAmount() * 10000 )/ 100)` y una prueba con  `intval($item->getTaxAmount() * 10000 )/ 100)` ? entiendo, alguno de esos productos que tu detectaste tienen alguna caracteristica especial, son productos compuestos, virtuales o algo en que se diferencien estos productos que estan registrando un tax ?

**Comment by MrDavidChz** [comment]
el resultado es el mismo para ambos casos floatval e intval.
![image](https://user-images.githubusercontent.com/34451939/40386324-0ad1a382-5dcf-11e8-979c-b8c39ea5b7b1.png)
![image](https://user-images.githubusercontent.com/34451939/40386356-1d692826-5dcf-11e8-83e5-aa829a6c2040.png)
Fíjate que solo cambie el precio quitando los centavos y funciono correctamente. Así que el problema es en los centavos ya que no tiene ninguna característica especial.
![image](https://user-images.githubusercontent.com/34451939/40386443-5ab272b4-5dcf-11e8-8890-b4a5778e0eaa.png)

La verdad no se en que parte modificar para solucionar este problema con los centavos.
inicialice en la linea  $tax_line["amount"]      = 0 ;  
Pero sigue sin funcionar, que podrá ser ?

**Comment by edenriquez** [comment]
@MrDavidChz hay un proceso que se llama `checkBalance` que revisa que el monto total de la orden coincida con la suma del carrito, taxes, discount lines(cupones) etc y eso podria estar afectando el balance precisamente no coincide el redondeo inicial que hacemos contra la suma final, pero debe ser por los centavos por ser decimales y nosotros convertir las cantidades siempre * 100 no podemos tener control en decimales muy largos

**Comment by MrDavidChz** [comment]
y habrá alguna actualización de su parte para resolver este tema ?

**Comment by edenriquez** [comment]
claro en un futuro lo arreglaremos por lo pronto te recomendaríamos no tener decimales muy específicos en tus items, y una disculpa por los inconvenientes @MrDavidChz

**Comment by MrDavidChz** [comment]
Ok, Muchas Gracias por el apoyo ya pude resolverlo modificando la función de checkBalance .
