### ISSUE TITLE
Need to increase security for Webhooks Controller

### ISSUE THREAD

**Issue by MauricioMurga** [conekta/conekta-magento#7]
Validate that the event notification comes from Conekta.

**Comment by lancasterjones** [comment]
Recomiendo usar un valor que venga codificado en BASE64 para validar que el llamado venga directo de Conekta.

**Comment by MauricioMurga** [comment]
Hola @lancasterjones, muchas gracias por tu comentario. Ya hemos habilitado una funcionalidad en el API que permitirá que en el próximo release de Magento 1, exista autenticación como lo mencionas.
