### ISSUE TITLE
español

### ISSUE THREAD

**Issue by rockdrigo** [conekta/conekta-magento#8]
tengo varias preguntas
Si conekta es empresa mexicana por que no poner todo en español?
o al menos un archvio de traducciones??
pues veo unos "echo" en español y otros en ingles 
y por ultimo, la verion 0.4.6 ya es estable?? y ya esta actualizada en magento connect??

y al ser una extension de pago se que es dificil que acepten pullrequests pero aceptarian quemandara la traduccion al español? esto para saber si la subo 

gracias!

**Comment by MauricioMurga** [comment]
Hola @rockdrigo, estamos abiertos a PR y si creas uno sería el primero para este plugin.

Para contestar tu pregunta, las versiones que se presentan en github siempre están actualizadas con lo que se tiene en MagentoConnect.
