### ISSUE TITLE
  "message": "A line item description is missing in line_items.",

### ISSUE THREAD

**Issue by jpaezsa** [conekta/conekta-magento#9]
Llevo 1 semana con el equipo de soporte por email y teléfono incluso he hablado con Victor y no me pueden dar una solución.

Tengo error >   "message": "A line item description is missing in line_items.", como podemos solventar para poder realizar la transacción porfa!

=======>
Resumen

Id5660e553241229245700008f
Fecha12/03/15 18:58
MétodoPOST
URL/charges
Status422
Dirección IP50.87.144.XX
Versión
Petición Query String

Query string no disponible.
Petición: Cuerpo de petición

{
  "card": "tok_3nK2S8aWDqJe4JnSJ",
  "currency": "MXN",
  "amount": "45421",
  "description": "Compra en Magento",
  "reference_id": "100000017",

Cuerpo de la Respuesta

{
  "object": "error",
  "type": null,
  "message": "A line item description is missing in line_items.",
  "message_to_purchaser": "Falta una descripción de un producto en tu orden en el campo de line_item.",
  "param": null,
  "code": "parameter_validation"
}

**Comment by MauricioMurga** [comment]
Hola @jpaezsa, creo que ya resolvimos este tema via e-mail pero dejo la solución por aquí por si alguien lo necesita:
1) Hay que agregar la descripción de los productos en el catálogo y configurarlo como valor obligatorio para creación de nuevos.
2) Hay que habilitar este atributo de manera global para que sea accesible desde el plugin.

Saludos!
